<?xml version="1.0" ?>
<!DOCTYPE All [ 
<!ELEMENT All (ServiceLetList+,JSONServiceLetList+,ExterneModulDescriptors*,Jsp_Tag_OK_List+)>
<!ELEMENT ServiceLetList (ServiceLet+,interpreter+)>
<!ELEMENT ServiceLet (Synonyme)>
<!ELEMENT interpreter (Synonyme)>
<!ELEMENT Synonyme (#PCDATA)>

<!ATTLIST ServiceLet Name CDATA #REQUIRED>
<!ATTLIST interpreter Name CDATA #REQUIRED>

<!ELEMENT JSONServiceLetList (JSONServiceLet+)>
<!ELEMENT JSONServiceLet (JSONSynonyme)>
<!ELEMENT JSONSynonyme (#PCDATA)>
<!ATTLIST JSONServiceLet Name CDATA #REQUIRED>

<!ELEMENT ExterneModulDescriptors (ExterneModulDescriptor+)>
<!ATTLIST ExterneModulDescriptor name CDATA #REQUIRED>
<!ATTLIST ExterneModulDescriptor vesrionWeb CDATA #REQUIRED>

<!ELEMENT WebSERVServiceLetList (WebSERVServiceLet+)>
<!ELEMENT WebSERVServiceLet (WebSERVSynonyme)>
<!ELEMENT WebSERVSynonyme (#PCDATA)>
<!ATTLIST WebSERVServiceLet Name CDATA #REQUIRED>

<!ELEMENT Jsp_Tag_OK_List (Jsp_Tag_OK+)>
<!ELEMENT Jsp_Tag_OK (#PCDATA)>
<!ATTLIST Jsp_Tag_OK Name CDATA #REQUIRED>
<!ATTLIST Jsp_Tag_OK FieldName CDATA #REQUIRED>
]>
<All>
<ServiceLetList>
<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.accueil.AccueilDynamiqueServiceLet">
<Synonyme>AccueilDynamiqueServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.accueil.AccueilDynamiqueSsLiensServiceLet">
<Synonyme>AccueilDynamiqueSsLiensServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.accueil.PersoAccueilServiceLet">
<Synonyme>PersoAccueilServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.accueil.PersoAccueilCMSServiceLet">
<Synonyme>PersoAccueilCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.accueil.AlerteAccueilServiceLet">
<Synonyme>AlerteAccueilServiceLet</Synonyme>
</ServiceLet>


<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.accueil.AdministrationAccueilServiceLet">
<Synonyme>AdministrationAccueilServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.accueil.AdministrationParametrageAccueilServiceLet">
<Synonyme>AdministrationParametrageAccueilServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.StdErreurServiceLet">
<Synonyme>StdErreurServiceLet</Synonyme>
</ServiceLet>	

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.StdErreurServiceLetCMS">
<Synonyme>StdErreurServiceLetCMS</Synonyme>
</ServiceLet>					

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.StatsPagesServiceLet">
<Synonyme>StatsPagesServiceLet</Synonyme>
</ServiceLet>	     

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.StatGraphServicelet">
<Synonyme>StatGraphServicelet</Synonyme>
</ServiceLet>	     

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.StatsIDatesServiceLet">
<Synonyme>StatsIDatesServiceLet</Synonyme>
</ServiceLet>
	 
<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.TracesHostServiceLet">
<Synonyme>TracesHostServiceLet</Synonyme>
</ServiceLet>
	 
<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.VosAlertExpertServiceLet">
<Synonyme>VosAlertExpertServiceLet</Synonyme>
</ServiceLet>	 

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestSchTablServiceLet">
<Synonyme>GestSchTablServiceLet</Synonyme>
</ServiceLet>	 

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestSchMenuServiceLet">
<Synonyme>GestSchMenuServiceLet</Synonyme>
</ServiceLet>	

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestSchMenuCMServiceLet">
<Synonyme>GestSchMenuCMServiceLet</Synonyme>
</ServiceLet>	

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestSchTableCMServiceLet">
<Synonyme>GestSchTableCMServiceLet</Synonyme>
</ServiceLet>	

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.TracesDownloadServiceLet">
<Synonyme>TracesDownloadServiceLet</Synonyme>
</ServiceLet>	

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.pagesModalServiceLet">
<Synonyme>pagesModalServiceLet</Synonyme>
</ServiceLet>	

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.pagesModalServiceLetCMS">
<Synonyme>pagesModalServiceLetCMS</Synonyme>
</ServiceLet>	

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestElemServiceLet">
<Synonyme>GestElemServiceLet</Synonyme>
</ServiceLet>	

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestElemCMServiceLet">
<Synonyme>GestElemCMServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestionProfilServiceLet">
<Synonyme>GestionProfilServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestionProfilCMServiceLet">
<Synonyme>GestionProfilCMServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestionProfilRoleServiceLet">
<Synonyme>GestionProfilRoleServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.visuSchemaServiceLet">
<Synonyme>visuSchemaServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.VisuExpertServiceLet">
<Synonyme>VisuExpertServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestBandauxServiceLet">
<Synonyme>GestBandauxServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestionBandeauxCMServiceLet">
<Synonyme>GestionBandeauxCMServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.ConfigUserNSServiceLet">
<Synonyme>ConfigUserNSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.DetailUserServiceLet">
<Synonyme>DetailUserServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.UserInGestilServiceLet">
<Synonyme>UserInGestilServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.SearchUserServiceLet">
<Synonyme>SearchUserServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestionNivStructServiceLet">
<Synonyme>GestionNivStructServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestionPagesMiServiceLet">
<Synonyme>GestionPagesMiServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.DeplacElemServiceLet">
<Synonyme>DeplacElemServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestionUser_WDServiceLet">
<Synonyme>GestionUser_WDServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestionUser_WD_CMServiceLet">
<Synonyme>GestionUser_WD_CMServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestionWebDirServiceLet">
<Synonyme>GestionWebDirServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestionWebDirCMServiceLet">
<Synonyme>GestionWebDirCMServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.ModifLibElemServiceLet">
<Synonyme>ModifLibElemServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestionEcransLogiquesServiceLet">
<Synonyme>GestionEcransLogiquesServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.EcranLogiqueCMServiceLet">
<Synonyme>EcranLogiqueCMServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.PublicationAlertExpertServiceLet">
<Synonyme>PublicationAlertExpertServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.PublicationAlertExpertCMSServiceLet">
<Synonyme>PublicationAlertExpertCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.GestionAppelsTableServiceLet">
<Synonyme>GestionAppelsTableServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.SecuDomaineFormationServiceLet">
<Synonyme>SecuDomaineFormationServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.DemandeRetourReferentielServiceLet">
<Synonyme>DemandeRetourReferentielServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.ConnexionStatutServiceLet">
<Synonyme>ConnexionStatutServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.ElementPurgeCMSServiceLet">
<Synonyme>ElementPurgeCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.objects.Traitement_FichierAPurgerSousRep">
<Synonyme>Traitement_FichierAPurgerSousRep</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.objects.purge.Traitement_PurgeTableGapTrtDoc">
<Synonyme>Traitement_PurgeTableGapTrtDoc</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.webform.traitement.Traitement_ETL">
<Synonyme>Traitement_ETL</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.objects.purge.Traitement_Purge_SYS_DEF_PURGE_TBL">
<Synonyme>Traitement_Purge_SYS_DEF_PURGE_TBL</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.maj_si.ExportElementServiceLet">
<Synonyme>ExportElementServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.maj_si.ExportEnsembleServiceLet">
<Synonyme>ExportEnsembleServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.maj_si.ExportLancementServiceLet">
<Synonyme>ExportLancementServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.maj_si.ExportElementCMSServiceLet">
<Synonyme>ExportElementCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.maj_si.ExportEnsembleCMSServiceLet">
<Synonyme>ExportEnsembleCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.maj_si.ExportEnsembleDetailCMSServiceLet">
<Synonyme>ExportEnsembleDetailCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.maj_si.ExportCMSServiceLet">
<Synonyme>ExportCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.maj_si.ExportDossierServiceLet">
<Synonyme>ExportDossierServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.maj_si.ExportDossierCMSServiceLet">
<Synonyme>ExportDossierCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.maj_si.ExportParamDynamiqueServiceLet">
<Synonyme>ExportParamDynamiqueServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.purge.ParametragePurgeTablesServiceLet">
<Synonyme>ParametragePurgeTablesServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.purge.ParametragePurgeTablesAjoutModifServiceLet">
<Synonyme>ParametragePurgeTablesAjoutModifServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.purge.ParametragePurgeTablesAjoutModifTableLieeServiceLet">
<Synonyme>ParametragePurgeTablesAjoutModifTableLieeServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.TestSecuServiceLet">
<Synonyme>TestSecuServiceLet</Synonyme>
</ServiceLet>	

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.TestGenerePageServiceLet">
<Synonyme>TestGenerePageServiceLet</Synonyme>
</ServiceLet>	

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.CoherenceEnvironnementServiceLet">
<Synonyme>CoherenceEnvironnementServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.CoherenceEnvironnementCMSServiceLet">
<Synonyme>CoherenceEnvironnementCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.gestionExcel.XlsDocModelServiceLet">
<Synonyme>XlsDocModelServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.gestionExcel.ModelDuplicationServiceLet">
<Synonyme>ModelDuplicationServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.gestionExcel.XlsSheetModelServiceLet">
<Synonyme>XlsSheetModelServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.gestionExcel.LabelsEditorServiceLet">
<Synonyme>LabelsEditorServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.docserver.EditionDSLancementServiceLet">
<Synonyme>EditionDSLancementServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.UserServiceLet">
<Synonyme>UserServiceLet</Synonyme>
</ServiceLet>


<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.ContratCourantProfAjoutServiceLet">
<Synonyme>ContratCourantProfAjoutStdServiceLet</Synonyme>
</ServiceLet>


<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.paramecrandyn.ParametrageReglesGestionServiceLet">
<Synonyme>ParametrageReglesGestionServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.paramecrandyn.HistoriquesDesProjetsServiceLet">
<Synonyme>HistoriquesDesProjetsServiceLet</Synonyme>
</ServiceLet>


<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.objects.diffusion.Traitement_DiffusionDocument">
<Synonyme>Traitement_DiffusionDocument</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.structures.importexport.Traitement_ValidationImportStructuresEntite">
<Synonyme>Traitement_ValidationImportStructuresEntite</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.structures.importexport.Traitement_ValidationImportStructuresArbre">
<Synonyme>Traitement_ValidationImportStructuresArbre</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.structures.importexport.Traitement_ValidationImportStructuresResponsable">
<Synonyme>Traitement_ValidationImportStructuresResponsable</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.structures.importexport.Traitement_ValidationImportStructuresAffectation">
<Synonyme>Traitement_ValidationImportStructuresAffectation</Synonyme>
</ServiceLet>
<ServiceLet Name="fr.adp.com.gxp.std.mot_tech.lib.optiSecu.Traitement_OptiSecu">
<Synonyme>Traitement_OptiSecu</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.alert.batch.Traitement_Alerte">
<Synonyme>Traitement_Alerte</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.alert.batch.Traitement_AlerteEmail">
<Synonyme>Traitement_AlerteEmail</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.dpae.batch.Traitement_Dpae">
<Synonyme>Traitement_Dpae</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.admin.TestMailServiceLet">
<Synonyme>TestMailServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.delegation.DelegationServiceLet">
<Synonyme>DelegationServiceLet</Synonyme>
</ServiceLet>


<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.ReqEditionsCServiceLet">
<Synonyme>ReqEditionsCServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.ReqEditionsJKServiceLet">
<Synonyme>ReqEditionsJKServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.DashboardGrapheServiceLet">
<Synonyme>DashboardGrapheServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.DashboardGrapheAdminServiceLet">
<Synonyme>DashboardGrapheAdminServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.ReqEditionsServiceLet">
<Synonyme>ReqEditionsServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.DashboardToolServiceLet">
<Synonyme>DashboardToolServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.DashboardToolCMSServiceLet">
<Synonyme>DashboardToolCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.ReqEditionsTestCServiceLet">
<Synonyme>ReqEditionsTestCServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.ReqEditionsFCTServiceLet">
<Synonyme>ReqEditionsFCTServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.TemplatesEditionServiceLet">
<Synonyme>TemplatesEditionServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.ReqTexteModeleServiceLet">
<Synonyme>ReqTexteModeleServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.ModelePlanningServiceLet">
<Synonyme>ModelePlanningServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.ReqResultatServiceLet">
<Synonyme>ReqResultatServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.EtatsDeSortieServiceLet">
<Synonyme>EtatsDeSortieServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.FamilleEditionAjoutServiceLet">
<Synonyme>FamilleEditionAjoutServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.edition.ReqEditionsListePeopleServiceLet">
<Synonyme>ReqEditionsListePeopleServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.enquete.EnqueteAccServiceLet">
<Synonyme>EnqueteAccServiceLet</Synonyme>
</ServiceLet>
<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.enquete.PublicationEnqueteServiceLet">
<Synonyme>PublicationEnqueteServiceLet</Synonyme>
</ServiceLet>
<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.enquete.PublicationEnqueteCMSServiceLet">
<Synonyme>PublicationEnqueteCMSServiceLet</Synonyme>
</ServiceLet>
<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.enquete.PublicationEnqueteQuestServiceLet">
<Synonyme>PublicationEnqueteQuestServiceLet</Synonyme>
</ServiceLet>
<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.enquete.RepondreServiceLet">
<Synonyme>RepondreServiceLet</Synonyme>
</ServiceLet>
<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.enquete.ResultatsEnqServiceLet">
<Synonyme>ResultatsEnqServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.HelpDesk.HelpDeskCMSServiceLet">
<Synonyme>HelpDeskCMSServiceLet</Synonyme>
</ServiceLet>	

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.HelpDesk.HelpDeskServiceLet">
<Synonyme>HelpDeskServiceLet</Synonyme>
</ServiceLet>


<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.images.PersoImageServiceLet">
<Synonyme>PersoImageServiceLet</Synonyme>
</ServiceLet>
<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.images.PersoImageCMSServiceLet">
<Synonyme>PersoImageCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.images.ImageDispoServiceLet">
<Synonyme>ImageDispoServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.images.PhotoMatriculeServiceLet">
<Synonyme>PhotoMatriculeServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.index.IndexRechercheChainageAdminPopUpPagesServiceLet">
<Synonyme>IndexRechercheChainageAdminPopUpPagesServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.index.IndexRechercheChainageAdminPopUpChainagesServiceLet">
<Synonyme>IndexRechercheChainageAdminPopUpChainagesServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.index.IndexRechercheChainageAdminPopUpFiltresServiceLet">
<Synonyme>IndexRechercheChainageAdminPopUpFiltresServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.index.IndexRechercheChainageAdminServiceLet">
<Synonyme>IndexRechercheChainageAdminServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.index.IndexRechercheChainageServiceLet">
<Synonyme>IndexRechercheChainageServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.mailing.DefMailCMSServiceLet">
<Synonyme>DefMailCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.mailing.MsgGestionCMSServiceLet">
<Synonyme>MsgGestionCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.mailing.MsgGestionDetailServiceLet">
<Synonyme>MsgGestionDetailServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.mailing.MsgGestionServiceLet">
<Synonyme>MsgGestionServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.mailing.DefMailDetailServiceLet">
<Synonyme>DefMailDetailServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.mailing.DefBranchMailGenServiceLet">
<Synonyme>DefBranchMailGenServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.mailing.DefBranchMailGenChooseServiceLet">
<Synonyme>DefBranchMailGenChooseServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.mailing.DefMailParamFctCMSServiceLet">
<Synonyme>DefMailParamFctCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_met.lib.servicelet.mailing.DefMailServiceLet">
<Synonyme>DefMailServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_tech.lib.mail.Traitement_envoiMail">
<Synonyme>Traitement_envoiMail</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_tech.lib.mail.Traitement_MailIncoherences">
<Synonyme>Traitement_MailIncoherences</Synonyme>
</ServiceLet>


<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.administratif.common.ListeDiffusionServiceLet">
<Synonyme>ListeDiffusionStdServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.administratif.AttestSimpleServiceLet">
<Synonyme>AttestSimpleStdServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.mot_tech.lib.deploiement.Traitement_deploiement">
<Synonyme>Traitement_deploiement</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.dpae.DPAEServiceLet">
<Synonyme>DPAEServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.dpae.DPAEVisuServiceLet">
<Synonyme>DPAEVisuServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.dpae.DPAEHistoServiceLet">
<Synonyme>DPAEHistoServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.objects.dpae.traitements.Traitement_DPAE">
<Synonyme>Traitement_DPAE</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.objects.dpae.traitements.Traitement_DPAE_AR">
<Synonyme>Traitement_DPAE_AR</Synonyme>
</ServiceLet>


<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.ENFInterpreteur">
<Synonyme>ENFInterpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.EDI_DPAE_Interpreteur">
<Synonyme>EDI_DPAE_Interpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.EDI_GAP_Interpreteur">
<Synonyme>EDI_GAP_Interpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.EMB_EDI_Interpreteur">
<Synonyme>EMB_EDI_Interpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.AttestEdiInterpreter">
<Synonyme>AttestEdiInterpreter</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.MAJ_FIN_EMB_Interpreteur">
<Synonyme>MAJ_FIN_EMB_Interpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.MAJ_FIN_ANN_EMB_Interpreteur">
<Synonyme>MAJ_FIN_ANN_EMB_Interpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.CNTCourantInterpreteur">
<Synonyme>CNTCourantInterpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.MAJ_FIN_DEP_Interpreteur">
<Synonyme>MAJ_FIN_DEP_Interpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.MAJ_HISTO_EMPLOI_Interpreteur">
<Synonyme>MAJ_HISTO_EMPLOI_Interpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.ADZInterpreteur">
<Synonyme>ADZInterpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.ZIZInterpreteur">
<Synonyme>ZIZInterpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.PREInterpreteur">
<Synonyme>PREInterpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.WKF_MODIF_CNT_SELECT_Interpreteur">
<Synonyme>WKF_MODIF_CNT_SELECT_Interpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.WKF_SUSP_OP2_REPRISE_CONF_Interpreteur">
<Synonyme>WKF_SUSP_OP2_REPRISE_CONF_Interpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.MAJ_FIN_ACOMPTE_Interpreteur">
<Synonyme>MAJ_FIN_ACOMPTE_Interpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.structures.interpreteur.STEInterpreteur">
<Synonyme>STEInterpreteur</Synonyme>
</interpreter>

<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.structures.interpreteur.ETBInterpreteur">
<Synonyme>ETBInterpreteur</Synonyme>
</interpreter>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.GestionLHWServiceLet">
<Synonyme>GestionLHWServiceLet</Synonyme>
</ServiceLet>


<interpreter Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.interpreteur.MassAvantageInterpreter">
<Synonyme>MassAvantageInterpreter</Synonyme>
</interpreter>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.traitement.SelectionPacMatServiceLet">
<Synonyme>SelectionPacMatServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gap.traitement.SelectionPacMatCMSServiceLet">
<Synonyme>SelectionPacMatCMSServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gpec.AffectationEvenementServiceLet">
<Synonyme>AffectationEvenementServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gpec.AffectationEvenementAdministratifServiceLet">
<Synonyme>AffectationEvenementAdministratifServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gpec.AffectationEvenementStructureServiceLet">
<Synonyme>AffectationEvenementStructureServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gpec.AffectationPosteServiceLet">
<Synonyme>AffectationPosteServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gpec.AffectationPosteAjoutModifServiceLet">
<Synonyme>AffectationPosteAjoutModifServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gpec.AffectationPosteAjoutModifDerniereSituationServiceLet">
<Synonyme>AffectationPosteAjoutModifDerniereSituationServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gpec.AffectationSalarieAjoutServiceLet">
<Synonyme>AffectationSalarieAjoutServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gpec.AffectationSalarieAjoutModifLibreServiceLet">
<Synonyme>AffectationSalarieAjoutModifLibreServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gpec.AffectationSalarieModifServiceLet">
<Synonyme>AffectationSalarieModifServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gpec.AffectationSalarieServiceLet">
<Synonyme>AffectationSalarieServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gpec.AfficheNbEmploisParGrilleServiceLet">
<Synonyme>AfficheNbEmploisParGrilleServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gpec.AfficheNbPostesParGrilleServiceLet">
<Synonyme>AfficheNbPostesParGrilleServiceLet</Synonyme>
</ServiceLet>

<ServiceLet Name="fr.adp.com.gxp.std.modules.lib.servicelet.gpec.AjoutModifGrilleServicelet">
<Synonyme>AjoutModifGrilleServicelet</Synonyme>
</ServiceLet>
